### ISSUE TITLE
panic.py 빈 파일

### ISSUE THREAD

**Issue by hjoo3355** [social-infratech-dev-study/code-review-contest#12]
## Expected Behavior
빈 파일

## Actual Behavior
빈 파일

## Steps to Reproduce the Problem

  1. panic.py 실행 

## Specifications

  - latest commit; 
  - os;
  - python version;

**Comment by wyuinche** [comment]
수정해주세요~

**Comment by wyuinche** [comment]
이미 반영된 코드
