### ISSUE TITLE
loading.py 무한 루프 버그 

### ISSUE THREAD

**Issue by congchu** [social-infratech-dev-study/code-review-contest#15]
## Expected Behavior
유저가 입력한 초 만큼 loading 후 프로그램 종료

$ python3 loading.py
```shell
How many seconds?
>>> 2
loding starts

loading... 1
loading... 2

loading ends
```

## Actual Behavior
- 입력된 시간과 관계 없이 무한루프 

$ python3 loading.py
```shell
How many seconds?
>>> 2
loding starts

loading... 1
loading... 2
loading... 3
loading... 4
...
```

## Steps to Reproduce the Problem

  1. 10번째 라인 while문 조건 유저 입력 보다 작은 조건으로 수정 `while elapsed < n: `
  2. python3 loading.py

## Specifications

  - latest commit; 
  - os;
  - python version;

**Comment by wyuinche** [comment]
수정해주세요~
