### ISSUE TITLE
selection sort 함수 내용 없음

### ISSUE THREAD

**Issue by Geunbaek** [social-infratech-dev-study/code-review-contest#21]
## Expected Behavior
selection_sort 함수의 내용이 비어있음

## Actual Behavior
selection_sort 를 통해 배열 정렬

## Steps to Reproduce the Problem

  1. selection-sort.py 실행
  2.
  3.

## Specifications

  - latest commit; 
  - os;
  - python version;

**Comment by wyuinche** [comment]
수정해주세요~
